{"cells":[{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["(scimax-jupyter-advise)"]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["(scimax-jupyter-org-hydra/body)"]},{"cell_type":"markdown","metadata":{},"source":["    for i in range(3):\n        print(i)\n\n0\n1\n2\n\n    import numpy as np\n    np.linspace\n\n<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>\n\n    np.\n\n"]},{"cell_type":"markdown","metadata":{},"source":["### plotly\n\n"]},{"cell_type":"markdown","metadata":{},"source":["    from pycse.plotly import *\n    import plotly.express as px\n    \n    df = px.data.iris()\n    fig = px.scatter(df, x=\"sepal_width\", y=\"sepal_length\", color =\"species\",\n                     size =\"petal_length\", hover_data=['petal_width'])\n    fig.show()\n\nTypeErrorTraceback (most recent call last)\n<ipython-input-8-ddd507e31254> in <module>\n      5 fig = px.scatter(df, x=\"sepal\\_width\", y=\"sepal\\_length\", color `\"species\",\n      6                  size =\"petal_length\", hover_data`['petal\\_width'])\n-&#x2014;> 7 fig.show()\n\n~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, \\*args, \\*\\*kwargs)\n     28         f.write(html)\n     29 \n&#x2014;> 30     display(FileLink(fhtml, result\\_html\\_suffix=\"\"))\n     31 \n     32     return Image(pio.to\\_image(self, \"png\", engine=\"kaleido\"))\n\nTypeError: 'module' object is not callable\n\n    from pycse.orgmode import *\n    import matplotlib.pyplot as plt\n    \n    data = [['x', 'y'], None, [1, 2], [2, 4]]\n    org.table(data, name='table-data', caption='Data from a python table')\n    \n    print()\n    \n    plt.plot([4, 5, 6])\n    org.figure(plt.savefig('images/a-figure.png'), name='fig:1', caption='A figure in org-mode')\n\n:RESULTS:\n\nAttributeErrorTraceback (most recent call last)\n<ipython-input-9-1b87fd9b57c9> in <module>\n      3 \n      4 data = [['x', 'y'], None, [1, 2], [2, 4]]\n-&#x2014;> 5 org.table(data, name='table-data', caption='Data from a python table')\n      6 \n      7 print()\n\nAttributeError: module 'pycse.orgmode' has no attri [[\\*\\* plotly\n\n    from pycse.plotly import *\n    import plotly.express as px\n    \n    df = px.data.iris()\n    fig = px.scatter(df, x=\"sepal_width\", y=\"sepal_length\", color =\"species\",\n                     size =\"petal_length\", hover_data=['petal_width'])\n    fig.show()\n\n    import pycse.orgmode as org\n    import matplotlib.pyplot as plt\n    \n    data = [['x', 'y'], None, [1, 2], [2, 4]]\n    org.table(data, name='table-data', caption='Data from a python table')\n    \n    print()\n    \n    plt.plot([4, 5, 6])\n    org.figure(plt.savefig('images/a-figure.png'), name='fig:1', caption='A figure in org-mode')\n\n"]},{"cell_type":"markdown","metadata":{},"source":["#### test pyces\n\n"]},{"cell_type":"markdown","metadata":{},"source":["    from pycse.plotly import *\n    \n    import plotly.express as px\n    df = px.data.iris()\n    fig = px.scatter(df, x=\"sepal_width\", y=\"sepal_length\", color = \"species\", size = \"petal_length\", hover_data=['petal_width'])\n    \n    fig.show()\n\nTypeErrorTraceback (most recent call last)\n<ipython-input-1-0de3666b2768> in <module>\n      5 fig = px.scatter(df, x=\"sepal\\_width\", y=\"sepal\\_length\", color = \"species\", size = \"petal\\_length\", hover\\_data=['petal\\_width'])\n      6 \n-&#x2014;> 7 fig.show()\n\n~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, \\*args, \\*\\*kwargs)\n     28         f.write(html)\n     29 \n&#x2014;> 30     display(FileLink(fhtml, result\\_html\\_suffix=\"\"))\n     31 \n     32     return Image(pio.to\\_image(self, \"png\", engine=\"kaleido\"))\n\nTypeError: 'module' object is not callable\n\n]] bute 'table'\n\n"]},{"cell_type":"markdown","metadata":{},"source":["#### test pyces\n\n"]},{"cell_type":"markdown","metadata":{},"source":["    from pycse.plotly import *\n    \n    import plotly.express as px\n    df = px.data.iris()\n    fig = px.scatter(df, x=\"sepal_width\", y=\"sepal_length\", color = \"species\", size = \"petal_length\", hover_data=['petal_width'])\n    \n    fig.show()\n\nTypeErrorTraceback (most recent call last)\n<ipython-input-1-0de3666b2768> in <module>\n      5 fig = px.scatter(df, x=\"sepal\\_width\", y=\"sepal\\_length\", color = \"species\", size = \"petal\\_length\", hover\\_data=['petal\\_width'])\n      6 \n-&#x2014;> 7 fig.show()\n\n~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, \\*args, \\*\\*kwargs)\n     28         f.write(html)\n     29 \n&#x2014;> 30     display(FileLink(fhtml, result\\_html\\_suffix=\"\"))\n     31 \n     32     return Image(pio.to\\_image(self, \"png\", engine=\"kaleido\"))\n\nTypeError: 'module' object is not callable\n\n"]}],"metadata":[["org"],null,null],"nbformat":4,"nbformat_minor":0}